20020626

diff --git a/firewall b/firewall
--- a/firewall
+++ b/firewall
@@ -2,7 +2,7 @@
 #
 # firewall - http://fwup.org/
 #
-# Copyright (C) 1999-2001 raf <raf@raf.org>
+# Copyright (C) 1999-2002 raf <raf@raf.org>
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -22,12 +22,10 @@
 
 # firewall - control script for an ipchains packet filtering firewall
 #
-# chkconfig: 2345 09 91
+# chkconfig: 2345 00 99
 # description: Firewall provides network security and address/port translation
-# lockfile: /var/lock/subsys/firewall
-# config: /etc/firewall.policy
 #
-# 20010815 raf <raf@raf.org>
+# 20020626 raf <raf@raf.org>
 
 # Set the path explicitly
 
@@ -52,13 +50,16 @@ locate()
 	done
 }
 
-lock="/var/lock/subsys/firewall"
+[ -d /var/lock/subsys ] && lock="/var/lock/subsys/firewall" || lock=""
+[ -z "$lock" ] && [ -d /var/lock ] && lock="/var/lock/firewall"
+[ -z "$lock" ] && lock="/tmp/firewall.lock"
+
 policy="/etc/firewall.policy"
-fwup="`locate fwup`"
-fwdown="`locate fwdown`"
-ipchains="`locate ipchains`"
-ipmasqadm="`locate ipmasqadm`"
-ip="`locate ip`"
+fwup="$(locate fwup)"
+fwdown="$(locate fwdown)"
+ipchains="$(locate ipchains)"
+ipmasqadm="$(locate ipmasqadm)"
+ip="$(locate ip)"
 
 die()
 {
@@ -67,24 +68,45 @@ die()
 }
 
 # See how we were called
+
 case "$1" in
 
 	start|up)
-		[ -e "$lock" ] && die "The Firewall is already up"
+		[ -f "$lock" ] && die "The Firewall is already up"
 		[ -z "$fwup" ] && die "Failed to find executable fwup"
 		[ ! -r "$policy" ] && die "Failed to find readable $policy"
 		policy="$policy" "$fwup" && touch "$lock"
+		exit $?
 		;;
 
 	stop|down)
-		[ ! -e "$lock" ] && die "The Firewall is already down"
+		[ ! -f "$lock" ] && die "The Firewall is already down"
 		[ -z "$fwdown" ] && die "Failed to find executable fwdown"
 		[ ! -r $policy ] && die "Failed to find readable $policy"
 		policy="$policy" "$fwdown" && rm -f "$lock"
+		exit $?
+		;;
+
+	restart)
+		$0 stop && $0 start
+		exit $?
+		;;
+
+	reload|force-reload)
+		rm -f "$lock"
+		$0 start
+		exit $?
+		;;
+
+	reconf)
+		[ -z "$2" ] && die "usage: $0 reconf <config>"
+		[ -r "$policy.$2" ] || die "Failed to find readable policy: $policy.$2"
+		cat "$policy.$2" > "$policy" || die "Failed to reconfigure the firewall"
+		if [ -f "$lock" ]; then $0 reload; exit $?; fi
 		;;
 
 	status)
-		[ -e "$lock" ] && echo "The Firewall is up" || echo "The Firewall is down"
+		[ -f "$lock" ] && echo "The Firewall is up" || echo "The Firewall is down"
 		;;
 
 	probe)
@@ -124,18 +146,22 @@ case "$1" in
 		fi
 		;;
 
-	restart)
-		$0 stop
-		$0 start
-		;;
-
-	reload)
-		rm -f "$lock"
-		$0 start
+	*help)
+		echo "usage: $0 {start|stop|up|down|restart|[force-]reload|reconf <config>|status|probe|help}"
+		echo
+		echo "    start|up        - Start the firewall"
+		echo "    stop|down       - Stop the firewall"
+		echo "    restart         - Stop then start the firewall"
+		echo "    [force-]reload  - Faster than restart"
+		echo "    reconf <config> - Replace $policy with $policy.<config> then reload (if up)"
+		echo "    status          - Tell whether the firewall is up or down"
+		echo "    probe           - Show the state of the firewall in detail"
+		echo "    help            - Print this help"
+		echo
 		;;
 
 	*)
-		echo "usage: $0 {start|stop|up|down|restart|reload|status|probe}"
+		echo "usage: $0 {start|stop|up|down|restart|[force-]reload|reconf <config>|status|probe|help}"
 		exit 1
 		;;
 
diff --git a/meta-firewall b/meta-firewall
--- a/meta-firewall
+++ b/meta-firewall
@@ -2,7 +2,7 @@
 #
 # firewall - http://fwup.org/
 #
-# Copyright (C) 1999-2001 raf <raf@raf.org>
+# Copyright (C) 1999-2002 raf <raf@raf.org>
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -22,7 +22,7 @@
 
 # meta-firewall - control script for managing multiple remote firewalls
 #
-# 20010815 raf <raf@raf.org>
+# 20020626 raf <raf@raf.org>
 
 PATH=/sbin:/usr/sbin:/usr/local/sbin:/bin:/usr/bin:/usr/local/bin export PATH
 
@@ -59,16 +59,27 @@ remote()
 	done
 }
 
-[ -d "$mfwd" ] || die "failed to find $mfwd (check installation)"
+[ -z "$1" -o -d "$mfwd" ] || die "failed to find $mfwd (check installation)"
 
 case "$1" in
 
 	prepare)
 		[ -z "$2" ] && die "must specify a hostname"
 		[ -d "$mfwd/$2" ] || mkdir "$mfwd/$2" || die "failed to create $mfwd/$2"
-		[ -f "$mfwd/$2/firewall.policy" ] && die "refusing to overwrite $mfwd/$2/firewall.policy"
+		[ -f "$mfwd/$2/firewall.policy" ] && die "refusing to overwrite $mfwd/$2/firewall.policy (consider meta-firewall migrate)"
 		[ -f "$mfwd/firewall.policy" ] || die "failed to find $mfwd/firewall.policy (check installation)"
 		install "$mfwd/firewall.policy" "$mfwd/$2" || die "failed to cp $mfwd/firewall.policy $mfwd/$2"
+		chmod 600 "$mfwd/$2/firewall.policy" || die "failed to chmod 600 $mfwd/$2/firewall.policy"
+		;;
+
+	migrate)
+		[ -z "$2" ] && die "must specify a hostname"
+		[ -d "$mfwd/$2" ] || die "failed to find $mfwd/$2"
+		[ -f "$mfwd/$2/firewall.policy" ] || die "failed to find $mfwd/$2/firewall.policy"
+		[ -f "$mfwd/firewall.policy" ] || die "failed to find $mfwd/firewall.policy (check installation)"
+		mv "$mfwd/firewall.policy" "$mfwd/firewall.policy.bak" || die "failed to mv $mfwd/firewall.policy to $mfwd/firewall.policy.bak"
+		install "$mfwd/firewall.policy" "$mfwd/$2" || die "failed to cp $mfwd/firewall.policy $mfwd/$2"
+		"$mfwd/migrate-policy" -y "$mfwd/$2/firewall.policy" "$mfwd/$2/firewall.policy.bak" || die "failed to migrate $mfwd/$2/firewall.policy"
 		chmod 600 "$mfwd/$2/firewall.policy" || die "failed to chmod 600 $mfwd/$2/firewall.policy"
 		;;
 
@@ -123,6 +134,26 @@ case "$1" in
 		set +x
 		;;
 
+	diff)
+		[ -z "$2" ] && die "must specify a hostname"
+		[ -f "$mfwd/$2/firewall.policy" ] || die "failed to find $mfwd/$2/firewall.policy (prepare/edit/install/policy first)"
+		[ -d "$mfwd/tmp" ] || mkdir "$mfwd/tmp"
+		[ "$verbose" = "yes" ] && set -x
+		scp "$root@$target:/etc/firewall.policy" "$mfwd/tmp/policy.$target"  || die "failed to scp $target:/etc/firewall.policy"
+		diff -dsu "$mfwd/$target/firewall.policy" "$mfwd/tmp/policy.$target"
+		rm "$mfwd/tmp/policy.$target"
+		set +x
+		;;
+
+	revert)
+		[ -z "$2" ] && die "must specify a hostname"
+		[ -f "$mfwd/$2/firewall.policy" ] || die "failed to find $mfwd/$2/firewall.policy (prepare/edit first)"
+		[ "`diff \"$mfwd/$2/firewall.policy\" \"$mfwd/firewall.policy\"`" = "" ] && die "must prepare/read/understand/edit the policy file first"
+		[ "$verbose" = "yes" ] && set -x
+		scp "$root@$2:/etc/firewall.policy" "$mfwd/$2/firewall.policy" || die "failed to scp $2:/etc/firewall.policy to $mfwd/$2/firewall.policy"
+		set +x
+		;;
+
 	start|up|stop|down|restart|reload|status|probe)
 		remote $*
 		;;
@@ -131,15 +162,18 @@ case "$1" in
 		echo "usage: $0 <command> [host...]"
 		echo
 		echo " The following commands require a single hostname. You will need $root access"
-		echo " via openssh to this host. You will have to enter the remote $root password or"
-		echo " your passphrase twice. ssh-agent(1) can make this less tedious."
+		echo " via openssh to this host. You will need to enter the remote $root password"
+		echo " or your passphrase twice unless you use ssh-agent(1)."
 		echo
 		echo "  prepare   - Create a directory in $mfwd for the remote host"
+		echo "  migrate   - Migrate an existing policy file to a new policy file"
 		echo "  edit      - Edit the remote host's policy file"
 		echo "  install   - Install the firewall scripts onto the remote host"
 		echo "  policy    - Install the remote host's policy file"
 		echo "  uninstall - Uninstall the firewall from the remote host"
 		echo "  ls        - List the files related to the remote firewall installation"
+		echo "  diff      - Show the differences between local and remote policy files"
+		echo "  revert    - Copy the remote policy file over the local policy file"
 		echo
 		echo " The following commands take any number of hostnames as arguments. If there are"
 		echo " no hostname arguments, it defaults to all remote hosts for which a directory"
@@ -149,7 +183,7 @@ case "$1" in
 		echo "  start|up  - Start the remote firewall(s)"
 		echo "  stop|down - Stop the remote firewall(s)"
 		echo "  restart   - Restart the remote firewall(s)"
-		echo "  reload    - Reload the remote firewall(s) (quicker than restart)"
+		echo "  reload    - Reload the remote firewall(s) (a bit quicker than restart)"
 		echo "  status    - Show the status of the remote firewall(s)"
 		echo "  probe     - Show detailed status of the remote firewall(s)"
 		echo
@@ -160,6 +194,14 @@ case "$1" in
 		echo "  $0 install <fw>"
 		echo "  $0 policy <fw>"
 		echo "  $0 start"
+		echo
+		echo " A typical upgrade sequence is:"
+		echo
+		echo "  $0 migrate <fw>"
+		echo "  $0 edit <fw>"
+		echo "  $0 install <fw>"
+		echo "  $0 policy <fw>"
+		echo "  $0 restart"
 		echo
 		echo " A typical policy update sequence is:"
 		echo
